development:
  adapter: mysql2
  encoding: utf8
  database: pin-user-auth-development
  username: root
  password: root
  pool: 5
  timeout: 5000
  reconnect: true

test:
  adapter: mysql2
  encoding: utf8
  database: pin-user-auth-test
  username: root
  password: root
  pool: 5
  timeout: 5000
  
production:
  adapter: mysql2
  encoding: utf8
  database: pin-user-auth
  username: root
  password: [fill in on deploy]
  pool: 5
  timeout: 5000
  reconnect: true
